// Code generated by tools/test-gen/generate_tests.py. DO NOT EDIT.

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	aiozai "github.com/AIOZNetwork/aioz-ai-go-client"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/comment"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/discussion"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/reaction"
	"github.com/stretchr/testify/assert"
)

func TestGen_Discussions_PutApiKeyCommentsId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Comment.PutCommentsByID(
		comment.NewPutCommentsByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "PUT", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/comments")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PutApiKeyDatasetIdLike(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Reaction.PutDatasetByIDLike(
		reaction.NewPutDatasetByIDLikeParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "PUT", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/dataset")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_GetApiKeyDiscussionCompetitionId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Discussion.GetDiscussionCompetitionByID(
		discussion.NewGetDiscussionCompetitionByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PostApiKeyDiscussionCompetitionId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Discussion.PostDiscussionCompetitionByID(
		discussion.NewPostDiscussionCompetitionByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_GetApiKeyDiscussionDatasetId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Discussion.GetDiscussionDatasetByID(
		discussion.NewGetDiscussionDatasetByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion/dataset")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PostApiKeyDiscussionDatasetId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Discussion.PostDiscussionDatasetByID(
		discussion.NewPostDiscussionDatasetByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion/dataset")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_GetApiKeyDiscussionModelId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Discussion.GetDiscussionModelByID(
		discussion.NewGetDiscussionModelByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion/model")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PostApiKeyDiscussionModelId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Discussion.PostDiscussionModelByID(
		discussion.NewPostDiscussionModelByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion/model")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PutApiKeyDiscussionId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Discussion.PutDiscussionByID(
		discussion.NewPutDiscussionByIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "PUT", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_GetApiKeyDiscussionIdComments(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Comment.GetDiscussionByIDComments(
		comment.NewGetDiscussionByIDCommentsParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PostApiKeyDiscussionIdComments(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Comment.PostDiscussionByIDComments(
		comment.NewPostDiscussionByIDCommentsParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/discussion")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PutApiKeyItemsIdReact(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Reaction.PutItemsByIDReact(
		reaction.NewPutItemsByIDReactParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "PUT", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/items")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Discussions_PutApiKeyModelIdLike(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Discussions().Reaction.PutModelByIDLike(
		reaction.NewPutModelByIDLikeParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "PUT", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/model")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}
