// Code generated by tools/test-gen/generate_tests.py. DO NOT EDIT.

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	aiozai "github.com/AIOZNetwork/aioz-ai-go-client"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/api_key_storage"
	"github.com/stretchr/testify/assert"
)

func TestGen_Storage_PostApiKeyStorageUploadCreatePresignedUrl(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Storage().Storage.PostAPIKeyStorageUploadCreatePresignedURL(
		api_key_storage.NewPostAPIKeyStorageUploadCreatePresignedURLParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/storage/upload/create-presigned-url")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Storage_GetApiKeyStorageUploadStatistics(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Storage().Storage.GetAPIKeyStorageUploadStatistics(
		api_key_storage.NewGetAPIKeyStorageUploadStatisticsParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/storage/upload/statistics")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Storage_GetApiKeyStorageUploadFolder(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Storage().Storage.GetAPIKeyStorageUploadFolder(
		api_key_storage.NewGetAPIKeyStorageUploadFolderParams().WithContext(t.Context()).WithFolder("test-folder"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/storage/upload")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Storage_DeleteApiKeyStorageW3sUrl(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode("ok")
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	_, _ = client.Storage().Storage.DeleteAPIKeyStorageW3sURL(
		api_key_storage.NewDeleteAPIKeyStorageW3sURLParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "DELETE", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/storage/w3s/url")
	assert.Equal(t, "test-key", capturedAPIKey)
}
