// Code generated by tools/test-gen/generate_tests.py. DO NOT EDIT.

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	aiozai "github.com/AIOZNetwork/aioz-ai-go-client"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/api_key_organization"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/api_key_organization_wallet"
	"github.com/stretchr/testify/assert"
)

func TestGen_Organizations_PostApiKeyOrganization(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	_, _ = client.Organizations().Organization.PostAPIKeyOrganization(
		api_key_organization.NewPostAPIKeyOrganizationParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
}

func TestGen_Organizations_GetApiKeyOrganizationList(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetAPIKeyOrganizationList(
		api_key_organization.NewGetAPIKeyOrganizationListParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization/list")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_DeleteApiKeyOrganizationOrg(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.DeleteAPIKeyOrganizationOrg(
		api_key_organization.NewDeleteAPIKeyOrganizationOrgParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "DELETE", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrg(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetAPIKeyOrganizationOrg(
		api_key_organization.NewGetAPIKeyOrganizationOrgParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PatchApiKeyOrganizationOrgInfo(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.PatchAPIKeyOrganizationOrgInfo(
		api_key_organization.NewPatchAPIKeyOrganizationOrgInfoParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "PATCH", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgIsMember(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetAPIKeyOrganizationOrgIsMember(
		api_key_organization.NewGetAPIKeyOrganizationOrgIsMemberParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_DeleteApiKeyOrganizationOrgLeave(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.DeleteAPIKeyOrganizationOrgLeave(
		api_key_organization.NewDeleteAPIKeyOrganizationOrgLeaveParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "DELETE", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgMembers(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetAPIKeyOrganizationOrgMembers(
		api_key_organization.NewGetAPIKeyOrganizationOrgMembersParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgOffers(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetAPIKeyOrganizationOrgOffers(
		api_key_organization.NewGetAPIKeyOrganizationOrgOffersParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgPermission(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetAPIKeyOrganizationOrgPermission(
		api_key_organization.NewGetAPIKeyOrganizationOrgPermissionParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgSetting(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetAPIKeyOrganizationOrgSetting(
		api_key_organization.NewGetAPIKeyOrganizationOrgSettingParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PatchApiKeyOrganizationOrgSetting(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.PatchAPIKeyOrganizationOrgSetting(
		api_key_organization.NewPatchAPIKeyOrganizationOrgSettingParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "PATCH", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgStatisticsEarnings(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.PostAPIKeyOrganizationOrgStatisticsEarnings(
		api_key_organization_wallet.NewPostAPIKeyOrganizationOrgStatisticsEarningsParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgStatisticsSpendingCost(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.PostAPIKeyOrganizationOrgStatisticsSpendingCost(
		api_key_organization_wallet.NewPostAPIKeyOrganizationOrgStatisticsSpendingCostParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgWalletDepositHistory(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.GetAPIKeyOrganizationOrgWalletDepositHistory(
		api_key_organization_wallet.NewGetAPIKeyOrganizationOrgWalletDepositHistoryParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgWalletTransactionAnalytics(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.PostAPIKeyOrganizationOrgWalletTransactionAnalytics(
		api_key_organization_wallet.NewPostAPIKeyOrganizationOrgWalletTransactionAnalyticsParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgWalletTransactionHistory(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.GetAPIKeyOrganizationOrgWalletTransactionHistory(
		api_key_organization_wallet.NewGetAPIKeyOrganizationOrgWalletTransactionHistoryParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgWalletTransactionRecent(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.PostAPIKeyOrganizationOrgWalletTransactionRecent(
		api_key_organization_wallet.NewPostAPIKeyOrganizationOrgWalletTransactionRecentParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgWalletWithdrawEarnings(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.PostAPIKeyOrganizationOrgWalletWithdrawEarnings(
		api_key_organization_wallet.NewPostAPIKeyOrganizationOrgWalletWithdrawEarningsParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgWalletWithdrawHistory(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Wallet.GetAPIKeyOrganizationOrgWalletWithdrawHistory(
		api_key_organization_wallet.NewGetAPIKeyOrganizationOrgWalletWithdrawHistoryParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_DeleteApiKeyOrganizationOrgMember(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.DeleteAPIKeyOrganizationOrgMember(
		api_key_organization.NewDeleteAPIKeyOrganizationOrgMemberParams().WithContext(t.Context()).WithOrg("testorg").WithMember("testuser"),
		nil,
	)

	assert.Equal(t, "DELETE", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PatchApiKeyOrganizationOrgMember(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.PatchAPIKeyOrganizationOrgMember(
		api_key_organization.NewPatchAPIKeyOrganizationOrgMemberParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "PATCH", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}
