// Code generated by tools/test-gen/generate_tests.py. DO NOT EDIT.

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	aiozai "github.com/AIOZNetwork/aioz-ai-go-client"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/organization"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/organization_payment"
	"github.com/stretchr/testify/assert"
)

func TestGen_Organizations_GetApiKeyOrganizationList(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetOrganizationList(
		organization.NewGetOrganizationListParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization/list")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrg(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetOrganizationByOrg(
		organization.NewGetOrganizationByOrgParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PatchApiKeyOrganizationOrgInfo(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.PatchOrganizationByOrgInfo(
		organization.NewPatchOrganizationByOrgInfoParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "PATCH", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgMembers(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetOrganizationByOrgMembers(
		organization.NewGetOrganizationByOrgMembersParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgPermission(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Organization.GetOrganizationByOrgPermission(
		organization.NewGetOrganizationByOrgPermissionParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgStatisticsEarnings(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Payment.PostOrganizationByOrgStatisticsEarnings(
		organization_payment.NewPostOrganizationByOrgStatisticsEarningsParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgStatisticsSpendingCost(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Payment.PostOrganizationByOrgStatisticsSpendingCost(
		organization_payment.NewPostOrganizationByOrgStatisticsSpendingCostParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgWalletDepositHistory(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Payment.GetOrganizationByOrgWalletDepositHistory(
		organization_payment.NewGetOrganizationByOrgWalletDepositHistoryParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgWalletTransactionAnalytics(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Payment.PostOrganizationByOrgWalletTransactionAnalytics(
		organization_payment.NewPostOrganizationByOrgWalletTransactionAnalyticsParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgWalletTransactionHistory(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Payment.GetOrganizationByOrgWalletTransactionHistory(
		organization_payment.NewGetOrganizationByOrgWalletTransactionHistoryParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_PostApiKeyOrganizationOrgWalletTransactionRecent(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Payment.PostOrganizationByOrgWalletTransactionRecent(
		organization_payment.NewPostOrganizationByOrgWalletTransactionRecentParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Organizations_GetApiKeyOrganizationOrgWalletWithdrawHistory(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Organizations().Payment.GetOrganizationByOrgWalletWithdrawHistory(
		organization_payment.NewGetOrganizationByOrgWalletWithdrawHistoryParams().WithContext(t.Context()).WithOrg("testorg"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/organization")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}
