// Code generated by tools/test-gen/generate_tests.py. DO NOT EDIT.

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	aiozai "github.com/AIOZNetwork/aioz-ai-go-client"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public"
	"github.com/stretchr/testify/assert"
)

func TestGen_Public_PostApiKeyPublicCostEstimating(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.PostPublicCostEstimating(
		public.NewPostPublicCostEstimatingParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/public/cost/estimating")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetApiKeyPublicMetadata(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicMetadata(
		public.NewGetPublicMetadataParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/public/metadata")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetApiKeyPublicTokenPrice(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicTokenPrice(
		public.NewGetPublicTokenPriceParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/public/token/price")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetApiKeyPublicUserUsernameMedals(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicUserByUsernameMedals(
		public.NewGetPublicUserByUsernameMedalsParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/public/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetApiKeyPublicUserUsernameMedalsStatistics(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicUserByUsernameMedalsStatistics(
		public.NewGetPublicUserByUsernameMedalsStatisticsParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/public/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}
