// Code generated by tools/test-gen/generate_tests.py. DO NOT EDIT.

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	aiozai "github.com/AIOZNetwork/aioz-ai-go-client"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/api_key_competition"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/api_key_competition_leaderboard"
	"github.com/stretchr/testify/assert"
)

func TestGen_Competitions_PostApiKeyCompetition(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetition(
		api_key_competition.NewPostAPIKeyCompetitionParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PostApiKeyCompetitionList(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetitionList(
		api_key_competition.NewPostAPIKeyCompetitionListParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition/list")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_GetApiKeyCompetitionPathPath(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.GetAPIKeyCompetitionPathPath(
		api_key_competition.NewGetAPIKeyCompetitionPathPathParams().WithContext(t.Context()).WithPath("test-path"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition/path")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PostApiKeyCompetitionPreSubmit(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetitionPreSubmit(
		api_key_competition.NewPostAPIKeyCompetitionPreSubmitParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition/pre-submit")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PostApiKeyCompetitionSubmit(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetitionSubmit(
		api_key_competition.NewPostAPIKeyCompetitionSubmitParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition/submit")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PostApiKeyCompetitionSubmitCost(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetitionSubmitCost(
		api_key_competition.NewPostAPIKeyCompetitionSubmitCostParams().WithContext(t.Context()),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition/submit/cost")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_GetApiKeyCompetitionSubmitHistoryId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.GetAPIKeyCompetitionSubmitHistoryID(
		api_key_competition.NewGetAPIKeyCompetitionSubmitHistoryIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition/submit/history")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_DeleteApiKeyCompetitionId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.DeleteAPIKeyCompetitionID(
		api_key_competition.NewDeleteAPIKeyCompetitionIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "DELETE", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_GetApiKeyCompetitionId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.GetAPIKeyCompetitionID(
		api_key_competition.NewGetAPIKeyCompetitionIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PutApiKeyCompetitionId(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PutAPIKeyCompetitionID(
		api_key_competition.NewPutAPIKeyCompetitionIDParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "PUT", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PostApiKeyCompetitionIdJoin(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetitionIDJoin(
		api_key_competition.NewPostAPIKeyCompetitionIDJoinParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PostApiKeyCompetitionIdLaunch(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetitionIDLaunch(
		api_key_competition.NewPostAPIKeyCompetitionIDLaunchParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_GetApiKeyCompetitionIdLeaderboard(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Leaderboard.GetAPIKeyCompetitionIDLeaderboard(
		api_key_competition_leaderboard.NewGetAPIKeyCompetitionIDLeaderboardParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_PostApiKeyCompetitionIdLeave(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Competition.PostAPIKeyCompetitionIDLeave(
		api_key_competition.NewPostAPIKeyCompetitionIDLeaveParams().WithContext(t.Context()).WithID("test-id"),
		nil,
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Competitions_GetApiKeyCompetitionIdPublicLeaderboard(t *testing.T) {
	var capturedMethod, capturedPath string
	var capturedAPIKey string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedAPIKey = r.Header.Get("x-api-key")
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Competitions().Leaderboard.GetAPIKeyCompetitionIDPublicLeaderboard(
		api_key_competition_leaderboard.NewGetAPIKeyCompetitionIDPublicLeaderboardParams().WithContext(t.Context()).WithID("test-id").WithPhase("test-id"),
		nil,
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/api-key/competition")
	assert.Equal(t, "test-key", capturedAPIKey)
	assert.NoError(t, err)
	assert.NotNil(t, result)
}
