// Code generated by tools/test-gen/generate_tests.py. DO NOT EDIT.

package integration

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	aiozai "github.com/AIOZNetwork/aioz-ai-go-client"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public_collection"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public_competition"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public_dataset"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public_discussion"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public_medals"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public_model"
	"github.com/AIOZNetwork/aioz-ai-go-client/generated/client/public_organization"
	"github.com/stretchr/testify/assert"
)

func TestGen_Public_PostPublicCollectionList(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Collection.PostPublicCollectionList(
		public_collection.NewPostPublicCollectionListParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/collection/list")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCollectionId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Collection.GetPublicCollectionID(
		public_collection.NewGetPublicCollectionIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/collection")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicCollectionUsernameList(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Collection.PostPublicCollectionUsernameList(
		public_collection.NewPostPublicCollectionUsernameListParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/collection")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicCompetitionList(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.PostPublicCompetitionList(
		public_competition.NewPostPublicCompetitionListParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition/list")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCompetitionMetadata(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.GetPublicCompetitionMetadata(
		public_competition.NewGetPublicCompetitionMetadataParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition/metadata")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCompetitionPathPath(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.GetPublicCompetitionPathPath(
		public_competition.NewGetPublicCompetitionPathPathParams().WithContext(t.Context()).WithPath("test-path"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition/path")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCompetitionTimelineId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.GetPublicCompetitionTimelineID(
		public_competition.NewGetPublicCompetitionTimelineIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition/timeline")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCompetitionId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.GetPublicCompetitionID(
		public_competition.NewGetPublicCompetitionIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCompetitionIdLeaderboard(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.GetPublicCompetitionIDLeaderboard(
		public_competition.NewGetPublicCompetitionIDLeaderboardParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCompetitionIdPublicLeaderboard(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.GetPublicCompetitionIDPublicLeaderboard(
		public_competition.NewGetPublicCompetitionIDPublicLeaderboardParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicCompetitionIdTimelines(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Competition.GetPublicCompetitionIDTimelines(
		public_competition.NewGetPublicCompetitionIDTimelinesParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/competition")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicContentTermsPrivacy(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicContentTermsPrivacy(
		public.NewGetPublicContentTermsPrivacyParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/content/terms-privacy")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicContentKeys(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicContentKeys(
		public.NewGetPublicContentKeysParams().WithContext(t.Context()).WithKeys("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/content")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicCostEstimating(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.PostPublicCostEstimating(
		public.NewPostPublicCostEstimatingParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/cost/estimating")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicDatasetList(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Dataset.PostPublicDatasetList(
		public_dataset.NewPostPublicDatasetListParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset/list")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicDatasetListByAuthorUsername(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Dataset.PostPublicDatasetListByAuthorUsername(
		public_dataset.NewPostPublicDatasetListByAuthorUsernameParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset/list-by-author")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicDatasetMatchingTags(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode([]any{})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	_, _ = client.Public().Dataset.PostPublicDatasetMatchingTags(
		public_dataset.NewPostPublicDatasetMatchingTagsParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset/matching-tags")
}

func TestGen_Public_GetPublicDatasetMetadata(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Dataset.GetPublicDatasetMetadata(
		public_dataset.NewGetPublicDatasetMetadataParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset/metadata")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDatasetOrganizationOrg(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Dataset.GetPublicDatasetOrganizationOrg(
		public_dataset.NewGetPublicDatasetOrganizationOrgParams().WithContext(t.Context()).WithOrg("testorg"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset/organization")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDatasetTrending(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Dataset.GetPublicDatasetTrending(
		public_dataset.NewGetPublicDatasetTrendingParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset/trending")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDatasetId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Dataset.GetPublicDatasetID(
		public_dataset.NewGetPublicDatasetIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDatasetUsernameName(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Dataset.GetPublicDatasetUsernameName(
		public_dataset.NewGetPublicDatasetUsernameNameParams().WithContext(t.Context()).WithUsername("testuser").WithName("test-name"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/dataset")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDiscussionCompetitionId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Discussion.GetPublicDiscussionCompetitionID(
		public_discussion.NewGetPublicDiscussionCompetitionIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/discussion/competition")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDiscussionDatasetId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Discussion.GetPublicDiscussionDatasetID(
		public_discussion.NewGetPublicDiscussionDatasetIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/discussion/dataset")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDiscussionModelId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Discussion.GetPublicDiscussionModelID(
		public_discussion.NewGetPublicDiscussionModelIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/discussion/model")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDiscussionId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Discussion.GetPublicDiscussionID(
		public_discussion.NewGetPublicDiscussionIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/discussion")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicDiscussionIdComments(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Discussion.GetPublicDiscussionIDComments(
		public_discussion.NewGetPublicDiscussionIDCommentsParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/discussion")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicMetadata(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicMetadata(
		public.NewGetPublicMetadataParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/metadata")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicModelList(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.PostPublicModelList(
		public_model.NewPostPublicModelListParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model/list")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicModelListByAuthorUsername(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.PostPublicModelListByAuthorUsername(
		public_model.NewPostPublicModelListByAuthorUsernameParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model/list-by-author")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_PostPublicModelMatchingTags(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.PostPublicModelMatchingTags(
		public_model.NewPostPublicModelMatchingTagsParams().WithContext(t.Context()),
	)

	assert.Equal(t, "POST", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model/matching-tags")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicModelMetadata(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.GetPublicModelMetadata(
		public_model.NewGetPublicModelMetadataParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model/metadata")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicModelOrganizationOrg(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.GetPublicModelOrganizationOrg(
		public_model.NewGetPublicModelOrganizationOrgParams().WithContext(t.Context()).WithOrg("testorg"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model/organization")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicModelTrending(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.GetPublicModelTrending(
		public_model.NewGetPublicModelTrendingParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model/trending")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicModelId(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.GetPublicModelID(
		public_model.NewGetPublicModelIDParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicModelIdVersioning(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.GetPublicModelIDVersioning(
		public_model.NewGetPublicModelIDVersioningParams().WithContext(t.Context()).WithID("test-id"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicModelUsernameName(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Model.GetPublicModelUsernameName(
		public_model.NewGetPublicModelUsernameNameParams().WithContext(t.Context()).WithUsername("testuser").WithName("test-name"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/model")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicOrganization(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Organization.GetPublicOrganization(
		public_organization.NewGetPublicOrganizationParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/organization")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicOrganizationOrg(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Organization.GetPublicOrganizationOrg(
		public_organization.NewGetPublicOrganizationOrgParams().WithContext(t.Context()).WithOrg("testorg"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/organization")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicOrganizationOrgMembers(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Organization.GetPublicOrganizationOrgMembers(
		public_organization.NewGetPublicOrganizationOrgMembersParams().WithContext(t.Context()).WithOrg("testorg"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/organization")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicRepositoryOwnerusernameRepositorynameContentReadme(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicRepositoryOwnerUsernameRepositoryNameContentReadme(
		public.NewGetPublicRepositoryOwnerUsernameRepositoryNameContentReadmeParams().WithContext(t.Context()).WithOwnerUsername("testuser").WithRepositoryName("test-name"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/repository")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicSearch(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicSearch(
		public.NewGetPublicSearchParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/search")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicSearchUser(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicSearchUser(
		public.NewGetPublicSearchUserParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/search/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicTokenPrice(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicTokenPrice(
		public.NewGetPublicTokenPriceParams().WithContext(t.Context()),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/token/price")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicUserUsername(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicUserUsername(
		public.NewGetPublicUserUsernameParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicUserUsernameExisted(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicUserUsernameExisted(
		public.NewGetPublicUserUsernameExistedParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicUserUsernameMedals(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Medals.GetPublicUserUsernameMedals(
		public_medals.NewGetPublicUserUsernameMedalsParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicUserUsernameMedalsStatistics(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Medals.GetPublicUserUsernameMedalsStatistics(
		public_medals.NewGetPublicUserUsernameMedalsStatisticsParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}

func TestGen_Public_GetPublicUserUsernameOrganizations(t *testing.T) {
	var capturedMethod, capturedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": nil, "message": "", "status": "success"})
	}))
	defer server.Close()

	client, err := aiozai.NewClient(
		aiozai.WithAPIKey("test-key"),
		aiozai.WithBaseURL(server.URL+"/api/v1"),
	)
	if err != nil {
		t.Fatal(err)
	}

	result, err := client.Public().Public.GetPublicUserUsernameOrganizations(
		public.NewGetPublicUserUsernameOrganizationsParams().WithContext(t.Context()).WithUsername("testuser"),
	)

	assert.Equal(t, "GET", capturedMethod)
	assert.Contains(t, capturedPath, "/public/user")
	assert.NoError(t, err)
	assert.NotNil(t, result)
}
